(async()=>{
 const s=document.createElement('section');s.id='page-intro';s.className='page';s.innerHTML='<canvas id="film" width="1200" height="650" aria-label="Đế giày, FEA và kênh đã lưu Gen 1–3"></canvas>';
 document.querySelector('.hero').after(s);
 let playing=!matchMedia('(prefers-reduced-motion: reduce)').matches,time=playing?1:11,last=0;
 let d;try{const r=await fetch('/research/intro-data.json',{cache:'force-cache'});if(!r.ok)throw Error();d=await r.json();}catch{s.append(text('p','Chưa tải được hoạt cảnh.'));return;}
 const ctx=$('film').getContext('2d'),cache={},palette=['#286890','#58acaf','#acce93','#e7d482','#e69559','#b94c3b'];const all=d.t['1'].concat(d.t['2']),lo=Math.min(...all),hi=Math.max(...all);
 function color(t){const x=Math.max(0,Math.min(1,t))*5,i=Math.min(4,Math.floor(x)),f=x-i,a=palette[i].slice(1),b=palette[i+1].slice(1);return 'rgb('+[0,2,4].map(k=>Math.round(parseInt(a.slice(k,k+2),16)*(1-f)+parseInt(b.slice(k,k+2),16)*f)).join(',')+')';}
 function layer(key){if(cache[key])return cache[key];const c=document.createElement('canvas');c.width=1200;c.height=650;const g=c.getContext('2d');g.translate(600,325);g.scale(2.4,-2.4);d.f.forEach((f,i)=>{g.beginPath();f.forEach((id,j)=>j?g.lineTo(...d.v[id]):g.moveTo(...d.v[id]));g.closePath();g.fillStyle=d.t[key]?color((d.t[key][i]-lo)/(hi-lo)):'#82b9a5';g.fill();if(key==='mesh'){g.strokeStyle='#31594b66';g.lineWidth=.22;g.stroke();}});return cache[key]=c;}
 ['solid','mesh','1','2'].forEach(layer);
 let angle=0,zoom=1,drag=null;const film=$('film');film.style.touchAction='none';film.onpointerdown=e=>{drag=[e.clientX,e.clientY];film.setPointerCapture(e.pointerId);};film.onpointermove=e=>{if(!drag)return;angle+=(e.clientX-drag[0])*.006;zoom=Math.max(.5,Math.min(2,zoom-(e.clientY-drag[1])*.003));drag=[e.clientX,e.clientY];};film.onpointerup=film.onpointercancel=()=>drag=null;film.addEventListener('wheel',e=>{e.preventDefault();zoom=Math.max(.5,Math.min(2,zoom*Math.exp(-e.deltaY*.001)));},{passive:false});

 function frame(now){if(last&&playing&&!document.hidden&&!s.hidden&&!$('workspace').hidden)time=(time+(now-last)/1000)%15;last=now;ctx.clearRect(0,0,1200,650);ctx.save();ctx.globalAlpha=time>14.4?(15-time)/.6:Math.min(1,time/.6);ctx.translate(600,325);ctx.scale(zoom,zoom);ctx.rotate(angle-.07+.025*Math.sin(time*.3));ctx.translate(-600,-325);const key=time<2?'solid':time<4?'mesh':time<10?'1':'2';const previous=time<2?'solid':time<4?'solid':time<10?'mesh':'1',start=time<2?0:time<4?2:time<10?4:10,blend=Math.min(1,(time-start)/1.1);ctx.drawImage(layer(previous),0,0);ctx.globalAlpha=blend;ctx.drawImage(layer(key),0,0);ctx.globalAlpha=1;ctx.translate(600,325);ctx.scale(2.4,-2.4);
 if(time>=4){const gen=time<8?'1':time<12?'2':'3',start=gen==='1'?4:gen==='2'?8:12,p=Math.min(1,(time-start)/1.7),ease=p*p*(3-2*p),rows=d.n[gen],xs=rows.flatMap(r=>r.p.map(v=>v[0])),left=Math.min(...xs)-8,right=Math.max(...xs)+8;ctx.save();ctx.beginPath();ctx.rect(left,-200,(right-left)*ease,400);ctx.clip();ctx.lineCap='round';ctx.lineJoin='round';for(const [color,factor]of [['#345d50',1],['#b5dcca',.65]]){ctx.strokeStyle=color;for(const row of rows){ctx.lineWidth=row.d*factor;ctx.beginPath();row.p.forEach((v,i)=>i?ctx.lineTo(...v):ctx.moveTo(...v));ctx.stroke();}}ctx.restore();}

 if(time>6&&time<8||time>10&&time<12){const values=d.t[time<8?'1':'2'],threshold=Math.max(...values)-.3,chosen=[];ctx.strokeStyle='white';ctx.lineWidth=.8;values.forEach((v,i)=>{if(v<threshold)return;const p=[0,0];d.f[i].forEach(id=>{p[0]+=d.v[id][0]/3;p[1]+=d.v[id][1]/3;});if(chosen.some(q=>Math.hypot(q[0]-p[0],q[1]-p[1])<22))return;chosen.push(p);ctx.beginPath();ctx.arc(...p,9+3*Math.sin(time*5),0,Math.PI*2);ctx.stroke();});}ctx.restore();requestAnimationFrame(frame);}
 requestAnimationFrame(frame);
})();
