/* Saved mesh, temperatures and centerlines. Gen 3 retains Gen 2 FEA input. */
(async()=>{
 const section=document.createElement('section');section.id='page-intro';
 const canvas=document.createElement('canvas');canvas.id='film';canvas.tabIndex=0;canvas.setAttribute('aria-label','Đế giày 3D: kéo xoay, chụm hai ngón hoặc cuộn để phóng, chạm đúp để đặt lại');canvas.style.touchAction='none';section.append(canvas);document.querySelector('.hero').after(section);
 const gl=canvas.getContext('webgl',{alpha:true,antialias:true});if(!gl){section.append(text('p','Thiết bị chưa mở được WebGL.'));return;}
 try{
 const response=await fetch('/research/intro-data.json');if(!response.ok)throw Error('data');const d=await response.json();
 const unit=v=>{const n=Math.hypot(...v)||1;return v.map(x=>x/n)},cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],sub=(a,b)=>a.map((x,i)=>x-b[i]);
 const shader=(type,src)=>{const s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error('shader');return s;};
 const program=gl.createProgram();gl.attachShader(program,shader(gl.VERTEX_SHADER,`attribute vec3 p;attribute vec3 n;attribute vec2 temperature;uniform mat3 rotation;uniform vec2 scale;varying vec3 normal;varying vec2 heat;varying float x;void main(){vec3 q=rotation*p;normal=rotation*n;heat=temperature;x=p.x;gl_Position=vec4(q.x*scale.x,q.y*scale.y,-q.z*.25,1.);}`));
 gl.attachShader(program,shader(gl.FRAGMENT_SHADER,`precision mediump float;varying vec3 normal;varying vec2 heat;varying float x;uniform float thermal;uniform float mixGen;uniform float reveal;uniform bool tube;vec3 palette(float t){return t<.5?mix(vec3(.16,.42,.58),vec3(.78,.85,.55),t*2.):mix(vec3(.78,.85,.55),vec3(.76,.26,.15),(t-.5)*2.);}void main(){if(tube&&x>reveal)discard;float light=.6+.4*abs(dot(normalize(normal),normalize(vec3(-.3,.7,1.))));vec3 c=tube?vec3(.56,.79,.67):mix(vec3(.46,.71,.61),palette(clamp(mix(heat.x,heat.y,mixGen),0.,1.)),thermal);gl_FragColor=vec4(c*light,1.);}`));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error('program');gl.useProgram(program);gl.enable(gl.DEPTH_TEST);
 const at=Object.fromEntries(['p','n','temperature'].map(k=>[k,gl.getAttribLocation(program,k)])),u=Object.fromEntries(['rotation','scale','thermal','mixGen','reveal','tube'].map(k=>[k,gl.getUniformLocation(program,k)]));
 let radius=1;for(const v of d.v)radius=Math.max(radius,Math.hypot(...v));for(const rows of Object.values(d.n))for(const row of rows)for(const p of row.p)radius=Math.max(radius,Math.hypot(...p)+row.d/2);const factor=1/radius;
 let lo=Infinity,hi=-Infinity;for(const ts of Object.values(d.t))for(const t of ts)if(Number.isFinite(t)){lo=Math.min(lo,t);hi=Math.max(hi,t);}
 const mesh=[],normal=[],heat=[];d.f.forEach((f,i)=>{const pts=f.map(j=>d.v[j]),n=unit(cross(sub(pts[1],pts[0]),sub(pts[2],pts[0])));for(const p of pts){mesh.push(...p.map(x=>x*factor));normal.push(...n);heat.push((d.t['1'][i]-lo)/(hi-lo||1),(d.t['2'][i]-lo)/(hi-lo||1));}});
 function upload(p,n,t){return {count:p.length/3,buffers:[p,n,t].map(values=>{const b=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(values),gl.STATIC_DRAW);return b;})};}
 const part=upload(mesh,normal,heat),networks={};
 for(const [gen,rows] of Object.entries(d.n)){const ps=[],ns=[],ts=[];for(const row of rows){const rings=row.p.map((p,i)=>{const tangent=unit(sub(row.p[Math.min(i+1,row.p.length-1)],row.p[Math.max(i-1,0)])),a=unit(cross(tangent,Math.abs(tangent[2])>.9?[0,1,0]:[0,0,1])),b=cross(tangent,a);return Array.from({length:16},(_,j)=>{const angle=j*Math.PI/8,n=a.map((v,k)=>v*Math.cos(angle)+b[k]*Math.sin(angle));return {p:p.map((v,k)=>(v+row.d*.5*n[k])*factor),n};});});const emit=nodes=>{for(const v of nodes){ps.push(...v.p);ns.push(...v.n);ts.push(0,0);}};for(let i=1;i<rings.length;i++)for(let j=0;j<16;j++){const k=(j+1)%16;emit([rings[i-1][j],rings[i][j],rings[i][k],rings[i-1][j],rings[i][k],rings[i-1][k]]);}for(const end of [0,rings.length-1])for(let j=1;j<15;j++)emit([rings[end][0],rings[end][j],rings[end][j+1]]);}networks[gen]=upload(ps,ns,ts);}
 let yaw=.15,pitch=1.15,zoom=1,time=11,last=0;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,pointers=new Map();let distance=0,lastTap=0,moved=false;
 const gap=()=>{const p=[...pointers.values()];return p.length===2?Math.hypot(...sub(p[0],p[1])):0;};
 canvas.onpointerdown=e=>{if(e.pointerType==='mouse'&&e.button!==0)return;pointers.set(e.pointerId,[e.clientX,e.clientY]);canvas.setPointerCapture(e.pointerId);distance=gap();moved=false;};canvas.onpointermove=e=>{if(!pointers.has(e.pointerId))return;const previous=pointers.get(e.pointerId);pointers.set(e.pointerId,[e.clientX,e.clientY]);const dx=e.clientX-previous[0],dy=e.clientY-previous[1];if(Math.abs(dx)+Math.abs(dy)>1)moved=true;if(pointers.size===1){yaw+=dx*.009;pitch+=dy*.009;}else{const next=gap();if(distance)zoom=Math.max(.4,Math.min(4,zoom*next/distance));distance=next;}};
 const reset=()=>{yaw=.15;pitch=1.15;zoom=1;};function release(e){if(e.type==='pointerup'&&!moved&&pointers.size===1){if(performance.now()-lastTap<320)reset();lastTap=performance.now();}pointers.delete(e.pointerId);distance=gap();}for(const event of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(event,release);canvas.addEventListener('wheel',e=>{e.preventDefault();zoom=Math.max(.4,Math.min(4,zoom*Math.exp(-e.deltaY*(e.deltaMode===1?16:1)*.001)));},{passive:false});canvas.onkeydown=e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','-','0'].includes(e.key))return;e.preventDefault();if(e.key==='0')reset();if(e.key==='ArrowLeft')yaw-=.15;if(e.key==='ArrowRight')yaw+=.15;if(e.key==='ArrowUp')pitch-=.15;if(e.key==='ArrowDown')pitch+=.15;if(e.key==='+')zoom=Math.min(4,zoom*1.2);if(e.key==='-')zoom=Math.max(.4,zoom/1.2);};
 function render(now){requestAnimationFrame(render);if(document.hidden){last=now;return;}const dt=last?Math.min((now-last)/1000,.1):0;last=now;if(!reduced&&!pointers.size)time=(time+dt)%15;const rect=canvas.getBoundingClientRect(),ratio=Math.min(devicePixelRatio||1,2),w=Math.round(rect.width*ratio),h=Math.round(rect.height*ratio);if(!w||!h)return;if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;}gl.viewport(0,0,w,h);gl.clearColor(0,0,0,0);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);const c=Math.cos(yaw),s=Math.sin(yaw),a=Math.cos(pitch),b=Math.sin(pitch);gl.uniformMatrix3fv(u.rotation,false,new Float32Array([c,s*b,-s*a,0,a,b,s,-c*b,c*a]));const fit=.88*zoom*Math.min(1,w/h);gl.uniform2f(u.scale,fit,fit*w/h);gl.uniform1f(u.thermal,Math.max(0,Math.min(1,(time-3)/1.2)));gl.uniform1f(u.mixGen,Math.max(0,Math.min(1,(time-9)/1.5)));function draw(row,tube){gl.uniform1i(u.tube,tube);row.buffers.forEach((buffer,i)=>{const key=['p','n','temperature'][i];gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.enableVertexAttribArray(at[key]);gl.vertexAttribPointer(at[key],i===2?2:3,gl.FLOAT,false,0,0);});gl.drawArrays(gl.TRIANGLES,0,row.count);}draw(part,0);if(time>=4){const gen=time<8?'1':time<12?'2':'3',start=gen==='1'?4:gen==='2'?8:12;gl.uniform1f(u.reveal,-1+2*Math.min(1,(time-start)/1.7));draw(networks[gen],1);}}
 requestAnimationFrame(render);canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();section.append(text('p','Mất hiển thị 3D. Tải lại trang để khôi phục.'));});
 }catch(error){section.append(text('p','Chưa tải được mô hình 3D. Tải lại trang để thử lại.'));console.error(error);}
})();
