/* Explanatory animation, not solver output. No scientific result is fabricated. */
(()=>{
 const section=document.createElement('section');section.id='page-intro';section.className='page panel';
 section.innerHTML='<canvas id="intro-film" width="900" height="520" role="img" aria-label="Minh họa đế giày, chia lưới, bề dày, kênh và trường nhiệt qua ba thế hệ"></canvas><div class="intro-controls"><button id="intro-play" aria-label="Pause animation">Ⅱ</button><button id="intro-replay" aria-label="Replay animation">↻</button><small data-vi="Minh họa quy trình" data-en="Workflow illustration"></small></div><div id="intro-benefits" hidden><h2 data-vi="Từ thiết kế đến kiểm tra" data-en="From design to verification"></h2><div class="fields"><p data-vi="Tạo kênh theo hình học chi tiết" data-en="Build channels around the part"></p><p data-vi="So sánh nhiệt qua từng thế hệ" data-en="Compare temperatures across generations"></p><p data-vi="Học từ FEA để dự đoán thiết kế mới" data-en="Learn from FEA to predict new designs"></p></div></div>';
 document.querySelector('.hero').after(section);
 const nav=document.createElement('button');nav.dataset.page='intro';nav.dataset.vi='Tổng quan';nav.dataset.en='Overview';nav.onclick=()=>page('intro');$('nav').prepend(nav);page('intro');words();
 const canvas=$('intro-film'),ctx=canvas.getContext('2d'),reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;
 let elapsed=reduce?27:0,last=0,playing=!reduce;
 $('intro-play').textContent=playing?'Ⅱ':'▶';
 $('intro-play').onclick=()=>{playing=!playing;$('intro-play').textContent=playing?'Ⅱ':'▶';};
 $('intro-replay').onclick=()=>{elapsed=0;playing=true;$('intro-play').textContent='Ⅱ';};
 function outline(){ctx.beginPath();ctx.moveTo(-285,-36);ctx.bezierCurveTo(-320,-115,-194,-131,-85,-82);ctx.bezierCurveTo(-5,-52,17,-100,128,-120);ctx.bezierCurveTo(292,-149,344,-28,253,67);ctx.bezierCurveTo(179,147,35,81,-44,78);ctx.bezierCurveTo(-139,89,-245,121,-285,-36);ctx.closePath();}
 function channel(gen,progress){ctx.lineCap='round';ctx.lineJoin='round';ctx.strokeStyle='#ec9d48';ctx.lineWidth=10;ctx.setLineDash([1300]);ctx.lineDashOffset=1300*(1-progress);for(const side of [-1,1]){ctx.beginPath();ctx.moveTo(-350,side*42);ctx.bezierCurveTo(-170,side*85,-70,side*20,30,side*51);ctx.bezierCurveTo(150,side*89,235,side*74,350,side*42);ctx.stroke();if(gen>1){ctx.lineWidth=gen===3?5:7;for(let x=-170;x<210;x+=85){ctx.beginPath();ctx.moveTo(x,side*52);ctx.quadraticCurveTo(x+20,side*20,x+55,side*(gen===3?108:94));ctx.stroke();if(gen===3){ctx.beginPath();ctx.moveTo(x+32,side*67);ctx.lineTo(x+75,side*74);ctx.stroke();}}ctx.lineWidth=10;}}ctx.setLineDash([]);}
 function draw(now){if(last&&playing&&!document.hidden&&!section.hidden&&!$('workspace').hidden)elapsed=Math.min(28,elapsed+(now-last)/1000);last=now;const stage=Math.min(6,Math.floor(elapsed/4));ctx.clearRect(0,0,900,520);ctx.fillStyle='#f3f7f3';ctx.fillRect(0,0,900,520);ctx.save();ctx.translate(450,265);ctx.rotate(-.15);ctx.scale(1,.92);ctx.shadowColor='#163e3225';ctx.shadowBlur=30;ctx.shadowOffsetY=20;outline();ctx.fillStyle='#7dc0a4';ctx.fill();ctx.shadowBlur=0;ctx.shadowOffsetY=0;
 if(stage>=1){ctx.save();outline();ctx.clip();if(stage>=2){const gradient=ctx.createLinearGradient(-290,0,290,0);gradient.addColorStop(0,'#4787ab');gradient.addColorStop(.25,'#9dd090');gradient.addColorStop(.5,'#eedb79');gradient.addColorStop(.8,stage>=4?'#e97a51':'#e8b873');gradient.addColorStop(1,'#6faea2');ctx.fillStyle=gradient;ctx.fillRect(-330,-160,660,320);}if(stage===1||stage===2){ctx.strokeStyle='#214e4850';ctx.lineWidth=1;for(let y=-160;y<170;y+=24)for(let x=-330;x<330;x+=28){ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+28,y);ctx.lineTo(x+14,y+24);ctx.closePath();ctx.stroke();}}if(stage>=4){for(const x of [-185,135]){const heat=ctx.createRadialGradient(x,-20,5,x,-20,100);heat.addColorStop(0,'#dd613388');heat.addColorStop(1,'#dd613300');ctx.fillStyle=heat;ctx.fillRect(x-100,-120,200,200);}}ctx.restore();}
 if(stage>=3)channel(stage>=6?3:stage>=5?2:1,elapsed>=27?1:Math.min(1,(elapsed%4)/1.5));ctx.restore();
 for(let i=0;i<7;i++){ctx.beginPath();ctx.arc(378+i*24,475,4,0,Math.PI*2);ctx.fillStyle=i<=stage?'#087660':'#cad9d0';ctx.fill();}
 $('intro-benefits').hidden=elapsed<26;if(elapsed>=28){playing=false;$('intro-play').textContent='▶';}requestAnimationFrame(draw);}
 requestAnimationFrame(draw);
})();
