'use strict';
const $=id=>document.getElementById(id);
let lang=localStorage.getItem('research-language')||'vi', csrf='', catalog=null, currentJob=null, comparisonJob=null, busy=false;
const selected=new Set();
const t=(vi,en)=>lang==='vi'?vi:en;
function words(){document.documentElement.lang=lang;document.querySelectorAll('[data-vi]').forEach(el=>el.textContent=el.dataset[lang]);$('lang').textContent=lang==='vi'?'EN':'VI';$('thought').textContent=t('Hỏi gì đó','Ask a question');if(catalog)render();}
function status(text,error=false){$('status').textContent=text;$('pet').classList.toggle('error',error);}
const errors={research_login_required:['Cần mở link nghiên cứu đầy đủ.','Open the complete research link.'],worker_busy:['Máy đang xử lý một tác vụ. Đợi tác vụ đó hoàn tất.','The master is processing a task. Wait for it to finish.'],separate_doe:['Chọn DOE hoặc Gen cho từng lượt học.','Select DOE or Gen for each training run.'],select_cases:['Hãy chọn case trước.','Select cases first.'],no_training_cases:['Danh sách chưa có case train.','No training cases selected.'],invite_invalid:['Link không còn hợp lệ. Lấy link mới trên máy chủ.','Link invalid. Get a new link from the master.'],rate_limited:['Thử lại sau ít phút.','Try again in a few minutes.']};
async function api(path,payload){const opts={credentials:'same-origin',cache:'no-store'};if(payload!==undefined){opts.method='POST';opts.headers={'Content-Type':'application/json','X-CSRF-Token':csrf};opts.body=JSON.stringify(payload);}const response=await fetch(path,opts);const data=await response.json();if(!response.ok){const pair=errors[data.error];throw new Error(pair?t(...pair):data.error||'Request failed');}return data;}
function guarded(fn){return async event=>{try{await fn(event);}catch(error){status(error.message,true);}};}
function page(name){const top=window.scrollY;document.querySelectorAll('.page').forEach(el=>el.hidden=el.id!=='page-'+name);document.querySelectorAll('[data-page]').forEach(el=>{const active=el.dataset.page===name;el.classList.toggle('active',active);if(active)el.setAttribute('aria-current','page');else el.removeAttribute('aria-current');});const heading=document.querySelector('#page-'+name+' h2');if(heading){heading.tabIndex=-1;heading.focus({preventScroll:true});}window.scrollTo({top:Math.min(top,document.querySelector('main').offsetTop),behavior:'instant'});}
function text(tag,value,className){const el=document.createElement(tag);el.textContent=value??'';if(className)el.className=className;return el;}
function option(select,value,label){const el=document.createElement('option');el.value=value;el.textContent=label;select.append(el);}
function shown(){const groups=[...new Set(catalog.cases.map(c=>c.cohort))];if(groups.length===1)$('cohort').value=groups[0];return catalog.cases.filter(c=>c.cohort===$('cohort').value&&JSON.stringify([c.case_id,c.product_id,c.display_metadata]).toLowerCase().includes($('search').value.toLowerCase()));}
function selection(){const cases=catalog.cases.filter(c=>selected.has(c.id));const splits={train:0,validation:0,test:0};cases.forEach(c=>splits[c.training_partition||'train']++);const value=cases.length?`${cases.length} case · Train ${splits.train} · Validation ${splits.validation} · Test ${splits.test}`:t('Chọn case để train AI.','Select cases to train AI.');$('selected-count').textContent=value;$('train-selection').textContent=value;$('clear-selection').hidden=!cases.length;const valid=splits.train>0&&new Set(cases.map(c=>c.cohort)).size===1;$('to-train').disabled=!valid;$('to-train').textContent=t(`Train với ${cases.length} case →`,`Train with ${cases.length} cases →`);$('train-form').querySelector('button[type="submit"],button.primary').disabled=!valid;}
function shortCase(c){return `Gen ${c.generation??'—'} · ${String(c.id).slice(0,6).toUpperCase()}`;}
function table(){const body=$('cases');body.replaceChildren();for(const c of shown()){
 const row=document.createElement('tr'),cell=document.createElement('td'),check=document.createElement('input');
 check.type='checkbox';check.checked=selected.has(c.id);check.setAttribute('aria-label',t('Chọn ','Select ')+shortCase(c));
 check.onchange=()=>{check.checked?selected.add(c.id):selected.delete(c.id);selection();$('case-detail').textContent=JSON.stringify(c,null,2);};cell.append(check);row.append(cell);
 const m=c.display_metadata||{},missing=t('Chưa có','Not available');
 const product=String(m.product_name||'').replace(/\.step$/i,'');
 const title=/degiay/i.test(product)?t('Đế giày','Shoe sole'):/FILE TEST 1/i.test(product)?'TEST 1':product||t('Chi tiết chưa đặt tên','Unnamed part');
 const name=document.createElement('td'),detail=document.createElement('details');detail.className='case-name';name.append(text('strong',title));detail.append(text('summary',t('Chi tiết','Details')),text('code',`${c.case_id}\n${t('Mã hình học','Geometry ID')}: ${c.product_id||missing}\n${t('Số nút','Nodes')}: ${c.node_count??missing}`));name.append(detail);row.append(name);
 const flows=(m.inlet_conditions||[]).map(i=>i.inlet_flow_cc_s).filter(v=>Number.isFinite(v));
 const number=v=>v!==null&&v!==undefined&&v!==''&&Number.isFinite(Number(v))?Number(v).toLocaleString(lang==='vi'?'vi-VN':'en-GB',{maximumFractionDigits:2}):missing;
 const values=[c.generation,number(m.parent_diameter_mm),flows.length?[...new Set(flows)].map(number).join(' / '):missing,c.training_partition||'train',c.source_available?t('Có tệp FEA','FEA file available'):t('Thiếu tệp FEA','FEA file missing')];
 const labels=['Gen','D (mm)','Q (cc/s/inlet)',t('Tập dữ liệu','Split'),t('Dữ liệu','Data')];
 values.forEach((v,i)=>{const td=text('td',v);td.dataset.label=labels[i];row.append(td);});body.append(row);
 }if(!body.children.length){const row=document.createElement('tr'),cell=text('td',t('Không có case phù hợp.','No matching cases.'));cell.colSpan=7;row.append(cell);body.append(row);}const headings=['✓',t('Chi tiết','Part'),'Gen','D (mm)','Q (cc/s/inlet)',t('Tập dữ liệu','Split'),t('Dữ liệu','Data')];document.querySelectorAll('#page-cases th').forEach((el,i)=>el.textContent=headings[i]);$('search').placeholder=t('Tìm chi tiết hoặc case','Find a part or case');$('select-visible').textContent=t('Chọn tất cả kết quả','Select all results');$('select-visible').disabled=!shown().length;$('cohort').hidden=new Set(catalog.cases.map(c=>c.cohort)).size<2;selection();}
function modelName(m){const date=new Date(m.modified*1000).toLocaleString(lang==='vi'?'vi-VN':'en-GB');return `${date} · ${m.scope||'AI'} · epoch ${m.epoch??'—'}`;}
function render(){table();$('summary').textContent=t(`${catalog.cases.length} case · ${new Set(catalog.cases.map(c=>c.product_id)).size} hình học · ${catalog.models.length} model`,`${catalog.cases.length} cases · ${new Set(catalog.cases.map(c=>c.product_id)).size} geometries · ${catalog.models.length} models`);const oldCase=$('compare-case').value,oldModel=$('compare-model').value;$('compare-case').replaceChildren();catalog.cases.forEach(c=>option($('compare-case'),c.id,`${c.case_id} · ${c.training_partition||'train'}`));if(oldCase)$('compare-case').value=oldCase;$('compare-model').replaceChildren();$('models').replaceChildren();catalog.models.sort((a,b)=>b.modified-a.modified).forEach(m=>{option($('compare-model'),m.id,modelName(m));const card=text('div',modelName(m),'model');card.append(text('small',m.label));$('models').append(card);});if(oldModel)$('compare-model').value=oldModel;renderJobs();$('copy-link').hidden=!catalog.owner;}
function renderJobs(){const old=currentJob||$('jobs').value;$('jobs').replaceChildren();option($('jobs'),' ',t('Chọn lượt xử lý','Select a run'));catalog.jobs.slice().reverse().forEach(j=>option($('jobs'),j.id,`${new Date(j.created_at*1000).toLocaleString()} · ${j.kind} · ${j.status}`));if(old)$('jobs').value=old;}
async function refresh(){catalog=await api('/api/research/catalog');render();$('entry').hidden=true;$('workspace').hidden=false;$('connection').textContent=t('Máy chủ online','Master online');}
async function start(){status(t('Đang tải case…','Loading cases…'));try{csrf=(await api('/api/session')).csrf;const params=new URLSearchParams(location.hash.slice(1));const access=params.get('access')||sessionStorage.getItem('research-access');if(access){await api('/api/research/login',{token:access});sessionStorage.setItem('research-access',access);history.replaceState(null,'',location.pathname);}await refresh();status(t('Sẵn sàng.','Ready.'));}catch(error){$('connection').textContent=error.message;$('entry').hidden=false;}}
async function submit(payload){if(busy)return;busy=true;try{const j=await api('/api/research/jobs',payload);currentJob=j.id;sessionStorage.setItem('research-job',currentJob);await refresh();page(payload.kind==='compare'?'compare':'live');await poll();}finally{busy=false;}}
function chart(canvas,historyRows){const ctx=canvas.getContext('2d'),w=canvas.width,h=canvas.height;ctx.fillStyle='#fff';ctx.fillRect(0,0,w,h);ctx.fillStyle='#18372a';ctx.font='20px monospace';ctx.fillText(t('RMSE bề mặt (°C)','Surface RMSE (°C)'),55,35);const rows=historyRows.filter(r=>Number.isFinite(r.metrics?.surface_rmse_C));if(!rows.length){ctx.fillText(t('Chưa có epoch hoàn tất','No completed epoch'),55,h/2);return;}const values=rows.map(r=>r.metrics.surface_rmse_C),min=0,max=Math.max(...values,0.001)*1.1;ctx.font='16px monospace';ctx.strokeStyle='#d6e2d9';for(let i=0;i<5;i++){const y=65+(h-130)*i/4;ctx.beginPath();ctx.moveTo(55,y);ctx.lineTo(w-35,y);ctx.stroke();ctx.fillStyle='#475d50';ctx.fillText((max*(1-i/4)).toFixed(2),4,y+4);}ctx.strokeStyle='#087660';ctx.lineWidth=3;ctx.beginPath();rows.forEach((r,i)=>{const x=55+(w-90)*i/Math.max(1,rows.length-1),y=h-65-(h-130)*(values[i]-min)/max;i?ctx.lineTo(x,y):ctx.moveTo(x,y);});ctx.stroke();ctx.fillStyle='#18372a';ctx.fillText(`Epoch ${rows[0].epoch} → ${rows.at(-1).epoch} · ${rows.at(-1).metric_scope}`,55,h-20);}
function graph(canvas,g){const ctx=canvas.getContext('2d'),w=canvas.width,h=canvas.height;ctx.fillStyle='#fff';ctx.fillRect(0,0,w,h);if(!g?.points_mm?.length){ctx.fillStyle='#475d50';ctx.font='20px monospace';ctx.fillText(t('Đợi lượt học thực','Waiting for training'),35,h/2);return;}const pts=g.points_mm;const spans=[0,1,2].map(axis=>Math.max(...pts.map(p=>p[axis]))-Math.min(...pts.map(p=>p[axis])));const axes=[0,1,2].sort((a,b)=>spans[b]-spans[a]);const x0=Math.min(...pts.map(p=>p[axes[0]])),y0=Math.min(...pts.map(p=>p[axes[1]]));const scale=Math.min((w-60)/Math.max(spans[axes[0]],.001),(h-60)/Math.max(spans[axes[1]],.001));const xy=pts.map(p=>[30+(p[axes[0]]-x0)*scale,h-30-(p[axes[1]]-y0)*scale]);ctx.strokeStyle='#bedacf';ctx.lineWidth=.7;const edges=g.edge_index||[[],[]];ctx.beginPath();for(let i=0;i<edges[0].length;i++){const a=xy[edges[0][i]],b=xy[edges[1][i]];if(a&&b){ctx.moveTo(...a);ctx.lineTo(...b);}}ctx.stroke();const temps=g.predicted_temperature_C||[];const low=Math.min(...temps),high=Math.max(...temps);xy.forEach((p,i)=>{ctx.fillStyle=Number.isFinite(temps[i])?`hsl(${240-240*(temps[i]-low)/Math.max(high-low,.001)},75%,46%)`:'#087660';ctx.fillRect(p[0],p[1],2.5,2.5);});$('graph-note').textContent=`${g.case_id} · ${g.sampled_node_count}/${g.node_count} nodes · ${low.toFixed(2)}–${high.toFixed(2)} °C · ${t('Mẫu hiển thị từ lượt học thực','Display sample from real training')}`;}
async function poll(){if(!currentJob)return;const j=await api('/api/research/jobs/'+currentJob);$('job-state').textContent=`${j.kind} · ${j.status} · ${j.telemetry?.phase||''} ${j.telemetry?.epoch||''}`;$('log').textContent=j.log||'';$('stop').disabled=j.kind!=='train'||!['running','stopping'].includes(j.status);$('pet').classList.toggle('busy',j.status==='running');$('thought').textContent=j.status==='running'?t('Mình đang theo dõi.','I’m following along.'):t('Xem kết quả nhé.','Let’s check the results.');chart($('curve'),j.history||[]);graph($('mesh'),j.graph);if(j.comparison){comparisonJob=currentJob;$('comparison-scope').textContent=`${j.comparison.case_id} · ${j.comparison.scope} · ${t('So sánh chẩn đoán','Diagnostic comparison')}`;$('metrics').replaceChildren();Object.entries(j.comparison.metrics).filter(([k,v])=>typeof v==='number'&&/rmse|mae|Tmax|max_abs/.test(k)).forEach(([k,v])=>{const item=text('div',k,'metric');item.append(text('strong',v.toFixed(4)));$('metrics').append(item);});}if(j.status==='error')status(t('Tác vụ lỗi. Mở Log để xem nguyên nhân.','Task failed. Open Log for details.'),true);const idx=catalog.jobs.findIndex(v=>v.id===j.id);if(idx>=0)catalog.jobs[idx]=j;}
function download(name,blob){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function exported(name,comparison=false){const key=comparison?comparisonJob:currentJob;if(!key)throw new Error(t('Chưa có kết quả.','No result yet.'));const response=await fetch(`/api/research/exports/${key}/${name}`,{credentials:'same-origin'});if(!response.ok)throw new Error(t('Tệp chưa sẵn sàng.','File is not ready.'));download(name,await response.blob());}
$('lang').onclick=()=>{lang=lang==='vi'?'en':'vi';localStorage.setItem('research-language',lang);words();};$('nav').onclick=e=>{const b=e.target.closest('[data-page]');if(b)page(b.dataset.page);};$('pet').onclick=()=>page('assistant');$('retry').onclick=start;$('refresh').onclick=guarded(refresh);$('search').oninput=table;$('cohort').onchange=table;$('select-visible').onclick=()=>{shown().forEach(c=>selected.add(c.id));table();};$('clear-selection').onclick=()=>{selected.clear();table();};$('to-train').onclick=()=>page('train');$('train-form').onsubmit=guarded(async e=>{e.preventDefault();const payload={kind:'train',cases:[...selected],split_mode:$('split-mode').value};for(const f of ['epochs','hidden','steps','patience','rmse','mae'])payload[f]=Number($(f).value);await submit(payload);});$('compare-form').onsubmit=guarded(async e=>{e.preventDefault();await submit({kind:'compare',case:$('compare-case').value,model:$('compare-model').value});});$('jobs').onchange=guarded(async()=>{currentJob=$('jobs').value.trim();if(currentJob){sessionStorage.setItem('research-job',currentJob);await poll();}});$('stop').onclick=guarded(async()=>{await api(`/api/research/jobs/${currentJob}/stop`,{});await poll();});
$('import-form').onsubmit=guarded(async e=>{e.preventDefault();const upload=crypto.randomUUID().replaceAll('-','');for(const [part,id] of [['manifest','manifest'],['graph','graph-file'],['source','source-file']]){const file=$(id).files[0];if(!file)throw new Error('Missing '+part);status(t('Đang tải: ','Uploading: ')+file.name);const response=await fetch(`/api/research/upload/${upload}/${part}`,{method:'POST',credentials:'same-origin',headers:{'X-CSRF-Token':csrf,'Content-Type':'application/octet-stream'},body:file});if(!response.ok)throw new Error((await response.json()).error);}await submit({kind:'import',upload,partition:$('partition').value});});
$('save-curve').onclick=()=>$('curve').toBlob(b=>download('learning-curve.png',b));$('save-mesh').onclick=()=>$('mesh').toBlob(b=>download('learning-graph.png',b));$('save-log').onclick=guarded(()=>exported('training.log'));$('save-history').onclick=guarded(()=>exported('history.jsonl'));$('export-report').onclick=guarded(()=>exported('report.json',true));$('export-nodes').onclick=guarded(()=>exported('nodes.csv',true));$('export-comparison').onclick=guarded(()=>exported('comparison.log',true));$('copy-link').onclick=guarded(async()=>{const result=await api('/api/research/link');await navigator.clipboard.writeText(result.url);status(t('Đã sao chép link.','Link copied.'));});
$('chat-form').onsubmit=guarded(async e=>{e.preventDefault();const question=$('question').value.trim();$('question').value='';$('chat').append(text('p',question));const answer=text('p','…');$('chat').append(answer);const job=await api('/api/chat',{question,language:lang,history:[]});async function watch(){try{const state=await api('/api/jobs/'+job.id);smoothAnswer(answer,state.result?.answer||state.text||'', $('chat'));if(['queued','running'].includes(state.status))setTimeout(watch,400);else if(state.error)answer.textContent=state.error;}catch(error){answer.textContent=error.message;}}await watch();});
$('cohort').onchange=()=>{selected.clear();table();};
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&catalog)refresh().catch(e=>status(e.message,true));});
page('cases');words();currentJob=sessionStorage.getItem('research-job');start();setInterval(()=>{if(catalog&&currentJob)poll().catch(e=>status(e.message,true));},4000);
