'use strict';
const $ = id => document.getElementById(id);
const TEXT = {
 vi: {
  skip:'Đến nội dung',predict:'Dự đoán',results:'Kết quả',assistant:'Trợ lý',settings:'Cài đặt',masterNote:'Xử lý trên máy chủ. Không tải model về máy.',
  chooseCase:'Chọn case',checkInputs:'Xem đầu vào',viewResult:'Xem kết quả',publishedCases:'Case được công bố',filter:'Tìm hình học / case',searchPlaceholder:'Tên hình học hoặc case',
  noCases:'Chưa có case công bố',noCasesNote:'Chủ máy sẽ công bố model và đầu vào đã kiểm tra. Không dùng dữ liệu nghiên cứu riêng.',noMatches:'Không có case khớp từ khóa.',refresh:'Làm mới danh sách',inputs:'Đầu vào',frozen:'Đúng theo case',selectFirst:'Chọn case để xem hình học, mạng kênh, D, Q và process.',process:'Process & vật liệu',frozenNote:'Không đổi D/Q trên graph cũ. Case mới cần đủ mesh, mạng kênh và process.',run:'Dự đoán',cancel:'Dừng yêu cầu',
  noResult:'Chưa có kết quả',noResultNote:'Chọn case và chạy dự đoán. Không hiển thị số liệu mẫu như kết quả thật.',projection:'Bề mặt · hình chiếu XY · điểm hiển thị lấy mẫu',zoomOut:'Thu nhỏ',zoomIn:'Phóng to',resetView:'Khớp hình',predictionCaveat:'Dự đoán AI không thay thế kiểm chứng FEA. Kết quả này chưa chứng nhận độ đúng trên hình học mới.',exportResult:'Xuất JSON',exportChart:'Xuất hình PNG',
  askAnything:'Hỏi trợ lý',assistantCaveat:'LLM có thể trả lời sai. Không tự chạy mô phỏng, train hay đổi ACTIVE.',chatWelcome:'Bạn muốn hiểu phần nào? Chọn câu hỏi bên dưới hoặc nhập câu của bạn.',yourQuestion:'Câu hỏi của bạn',questionPlaceholder:'Nhập câu hỏi…',send:'Gửi',exportLog:'Xuất log',commonQuestions:'Hay gặp',
  display:'Hiển thị',languageLabel:'Ngôn ngữ',reducedMotion:'Giảm chuyển động',zoomNote:'Có thể phóng to chữ bằng trình duyệt. Không khóa zoom trên điện thoại.',installTitle:'Cài trên máy / điện thoại',installNote:'Cài lên màn hình chính. Model và dữ liệu vẫn ở máy chủ.',install:'Cài ứng dụng',privacy:'Quyền & dữ liệu',privacyNote:'Bản công khai chỉ xem case được công bố, dự đoán và hỏi đáp. Không có DOE, train hoặc dữ liệu riêng. Chat không lưu lâu dài trên trình duyệt.',offlineNote:'Máy chủ tắt hoặc mất mạng: không dự đoán hay hỏi LLM. Giao diện đã cài vẫn mở được.',footer:'USER · AI & TRỢ LÝ',askPet:'Nhấn để hỏi',newVersion:'Có bản cập nhật.',update:'Cập nhật',
  online:'Máy chủ online',connecting:'Đang kết nối',offline:'Mất kết nối',offlineBanner:'Chưa kết nối được máy chủ. Không có dự đoán mới; giao diện vẫn dùng được.',localPreview:'Bản kiểm tra trên máy chủ · chưa phải link Internet.',running:'Đang xử lý trên máy chủ…',cancelling:'Đang dừng yêu cầu…',cancelled:'Đã dừng yêu cầu.',complete:'Hoàn tất.',reconnecting:'Mất kết nối. Đang kiểm tra lại yêu cầu cũ; không chạy trùng.',
  request_failed:'Chưa hoàn tất. Kiểm tra runtime/model trên máy chủ rồi thử lại.',server_busy:'Máy chủ đang bận. Vui lòng gửi lại sau.',rate_limited:'Có nhiều yêu cầu liên tiếp. Chờ một phút rồi gửi lại.',request_already_running:'Yêu cầu trước vẫn đang chạy.',model_not_qualified:'Model chưa đủ điều kiện dự đoán công khai.',publication_changed:'Dữ liệu công bố đã thay đổi. Chủ máy cần kiểm tra lại.',choose_published_case:'Chọn một case đã công bố; không sửa D/Q trên graph cũ.',invalid_question:'Nhập câu hỏi từ 1 đến 3.000 ký tự.',invalid_session:'Phiên kết nối đã hết hạn. Làm mới trang.',request_too_large:'Nội dung quá dài. Rút gọn câu hỏi/lịch sử.',job_not_found:'Yêu cầu không còn trong phiên này.',genericError:'Không thực hiện được yêu cầu.',
  geometry:'Hình học',model:'Model',you:'Bạn',petName:'Trợ lý',min:'Bề mặt · thấp nhất',max:'Bề mặt · cao nhất',mean:'Bề mặt · trung bình P1',qualified:'Có thể dự đoán',unqualified:'Chưa đủ điều kiện',standalone:'Đã mở ở chế độ ứng dụng.',iosInstall:'iPhone/iPad: mở bằng Safari → Chia sẻ → Thêm vào MH chính → Mở như ứng dụng.',browserInstall:'Android/PC: menu trình duyệt → Cài ứng dụng / Thêm vào màn hình chính. Cần link HTTPS.',secureInstall:'Cài ứng dụng cần HTTPS (hoặc localhost khi kiểm tra).',updateDeferred:'Cập nhật sau khi yêu cầu hoàn tất và câu hỏi chưa gửi đã được xử lý.',thoughtIdle:'Mình ở đây.',thoughtRun:'Đang xử lý…',thoughtDone:'Xong rồi.',thoughtOffline:'Máy chủ chưa online.',thoughtError:'Cần kiểm tra lại.',
  titlePredict:['KÊNH LÀM MÁT.','TIẾN HÓA DẠNG SINH HỌC.'],titleResults:['KẾT QUẢ',''],titleAssistant:['CỨ HỎI.','MÌNH Ở ĐÂY.'],titleSettings:['GỌN NHẸ.','DÙNG MỌI NƠI.'],
  subPredict:'Chọn chi tiết, nhập D và Q để tạo kênh.',subResults:'Số liệu từ kết quả hiện tại.',subAssistant:'Hiểu chương trình, khuôn mẫu và những câu hỏi của bạn.',subSettings:'Ngôn ngữ, chuyển động và cài lên màn hình chính.',
  questions:['Chương trình này làm được gì?','Kênh làm mát ảnh hưởng thế nào?','Fill và packing khác nhau thế nào?','D và Q là gì?','Làm sao biết dự đoán AI có chính xác?','Vì sao máy chủ mất kết nối?']
 },
 en: {
  skip:'Skip to content',predict:'Predict',results:'Results',assistant:'Assistant',settings:'Settings',masterNote:'Processed on the master. No model download.',
  chooseCase:'Choose case',checkInputs:'Review inputs',viewResult:'View result',publishedCases:'Published cases',filter:'Find geometry / case',searchPlaceholder:'Geometry or case name',
  noCases:'No published cases yet',noCasesNote:'The owner will publish checked models and inputs. Private research data stays private.',noMatches:'No case matches your search.',refresh:'Refresh cases',inputs:'Inputs',frozen:'Case-specific',selectFirst:'Choose a case to review geometry, channels, D, Q and process.',process:'Process & material',frozenNote:'Do not change D/Q on an old graph. New cases need the correct mesh, channels and process.',run:'Predict',cancel:'Stop request',
  noResult:'No result yet',noResultNote:'Choose a case and run prediction. Example values are never presented as real results.',projection:'Surface · XY projection · sampled display points',zoomOut:'Zoom out',zoomIn:'Zoom in',resetView:'Fit view',predictionCaveat:'AI prediction does not replace FEA verification. This result does not certify accuracy on new geometry.',exportResult:'Export JSON',exportChart:'Export PNG',
  askAnything:'Ask the assistant',assistantCaveat:'The LLM can be wrong. It cannot simulate, train or change ACTIVE.',chatWelcome:'What would you like to understand? Choose a question below or enter your own.',yourQuestion:'Your question',questionPlaceholder:'Enter a question…',send:'Send',exportLog:'Export log',commonQuestions:'Common questions',
  display:'Display',languageLabel:'Language',reducedMotion:'Reduce motion',zoomNote:'Use browser zoom to enlarge text. Phone zoom is not disabled.',installTitle:'Install on desktop / phone',installNote:'Add to your home screen. Models and data stay on the master.',install:'Install app',privacy:'Access & data',privacyNote:'The public edition only offers published cases, prediction and chat. No DOE, training or private data. Chat is not stored persistently in the browser.',offlineNote:'Master off or offline: no prediction or LLM chat. The installed interface can still open.',footer:'USER · AI & ASSISTANT',askPet:'Tap to ask',newVersion:'An update is available.',update:'Update',
  online:'Master online',connecting:'Connecting',offline:'Disconnected',offlineBanner:'Cannot reach the master. No new prediction is available; the interface still works.',localPreview:'Local validation preview · not an Internet link.',running:'Processing on the master…',cancelling:'Stopping the request…',cancelled:'Request stopped.',complete:'Complete.',reconnecting:'Disconnected. Checking the existing request, not starting a duplicate.',
  request_failed:'Request incomplete. Check the runtime/model on the master, then try again.',server_busy:'The master is busy. Please try again later.',rate_limited:'Too many recent requests. Wait a minute before sending again.',request_already_running:'Your previous request is still running.',model_not_qualified:'Model is not qualified for public prediction.',publication_changed:'Published data changed. The owner needs to review it.',choose_published_case:'Choose a published case; do not edit D/Q on an old graph.',invalid_question:'Enter a question between 1 and 3,000 characters.',invalid_session:'Session expired. Refresh the page.',request_too_large:'Content too long. Shorten your question/history.',job_not_found:'Request is no longer in this session.',genericError:'Could not complete this request.',
  geometry:'Geometry',model:'Model',you:'You',petName:'Assistant',min:'Surface · minimum',max:'Surface · maximum',mean:'Surface · P1 mean',qualified:'Prediction available',unqualified:'Not qualified',standalone:'Already running as an installed app.',iosInstall:'iPhone/iPad: open in Safari → Share → Add to Home Screen → Open as Web App.',browserInstall:'Android/desktop: browser menu → Install app / Add to Home Screen. Requires an HTTPS link.',secureInstall:'Installation requires HTTPS (or localhost during testing).',updateDeferred:'Update after your request finishes and the unsent question has been handled.',thoughtIdle:'I’m here.',thoughtRun:'Working…',thoughtDone:'All done.',thoughtOffline:'Master is offline.',thoughtError:'Needs a check.',
  titlePredict:['BIO-INSPIRED.','EVOLUTIONARY COOLING CHANNELS.'],titleResults:['RESULTS',''],titleAssistant:['JUST ASK.','I’M HERE.'],titleSettings:['LIGHTWEIGHT.','ANYWHERE.'],
  subPredict:'Choose a part, then enter D and Q to create channels.',subResults:'Metrics from the current result.',subAssistant:'Understand the application, molding and your other questions.',subSettings:'Language, motion and home-screen installation.',
  questions:['What can this application do?','How do cooling channels affect a part?','How are filling and packing different?','What do D and Q mean?','How do I check whether AI is accurate?','Why is the master disconnected?']
 }
};
Object.assign(TEXT.vi, {
 petName:'Soun',
 thoughtIdle:'Hỏi gì đó',titleAssistant:['TRỢ LÝ',''],titleSettings:['CÀI ỨNG DỤNG',''],
 subAssistant:'Hiểu chương trình và các câu hỏi liên quan đến khuôn mẫu.',subSettings:'Cài ứng dụng, ngôn ngữ và hiển thị.',
 installTitle:'Cài ứng dụng',installGuide:'Hướng dẫn cài',installed:'Đã cài ứng dụng',installDismissed:'Bạn chưa cài ứng dụng.',installFailed:'Chưa mở được trình cài. Dùng menu trình duyệt để cài.',
 enterDQ:'Nhập D / Q',createChannel:'Tạo kênh',predictEvolve:'Dự đoán → tiến hóa',newDesign:'Thiết kế mới',
 diameterLabel:'Đường kính (mm)',flowLabel:'Q · mỗi inlet (cc/s)',
 rangeCaveat:'Phạm vi nghiên cứu, chưa chứng nhận sai số. Gen 2–3 kế thừa D/Q; đường kính nhánh theo luật tạo kênh.',
 fixedProcess:'Process cố định',createGen1:'Tạo Gen 1',predictCurrent:'Dự đoán Gen 1',createNext:'Tạo Gen 2',newChain:'Thiết kế khác',
 archivedCases:'Dự đoán lại case đã lưu',continueDesign:'Tiếp tục tiến hóa',designReady:'Kênh đã tạo. Chạy dự đoán cho mạng này.',
 designPredicted:'Đã dự đoán. Có thể tạo Gen tiếp theo.',designComplete:'Đã hoàn tất chuỗi Gen 1–3.',
 predict_parent_first:'Dự đoán Gen trước rồi mới tiến hóa.',design_out_of_range:'D/Q ngoài phạm vi hiển thị.',
 channel_or_mapping_failed:'Kênh mới chưa qua kiểm tra hình học. Gen trước được giữ nguyên.',
 design_prediction_failed:'Chưa dự đoán được mạng mới. Kênh vẫn giữ nguyên.',design_not_found:'Thiết kế hết hạn. Tạo chuỗi mới.',
 geometry_design_unavailable:'Chi tiết này chưa có bộ tạo kênh được công bố.',design_cancelled_or_timeout:'Đã dừng hoặc quá thời gian. Gen trước không bị thay đổi.',
 subPredict:'Nhập D/Q → tạo kênh → dự đoán → tiến hóa Gen 2–3.',privacyNote:'Bản công khai tạo kênh, dự đoán và hỏi đáp trên hình học được công bố. Không có DOE, train hoặc dữ liệu riêng.',
 noResultNote:'Tạo kênh rồi chạy dự đoán. Kết quả chưa được kiểm định FEA độc lập.',
 generated:'Đã tạo',predicted:'Đã dự đoán',waiting:'Chưa tạo',view:'Xem',network:'Mạng kênh',circuits:'Mạch',segments:'Đoạn',length:'Chiều dài (mm)',researchRange:'Phạm vi nhập',lockedDQ:'D/Q giữ nguyên trong chuỗi. Chọn Thiết kế khác để đổi.'
});
Object.assign(TEXT.en, {
 petName:'Soun',
 thoughtIdle:'Ask a question',titleAssistant:['ASSISTANT',''],titleSettings:['INSTALL APP',''],
 subAssistant:'Questions about the application and mold design.',subSettings:'Installation, language and display.',
 installTitle:'Install app',installGuide:'Installation guide',installed:'App installed',installDismissed:'The app was not installed.',installFailed:'Could not open installation. Use the browser menu to install.',
 enterDQ:'Enter D / Q',createChannel:'Create channels',predictEvolve:'Predict → evolve',newDesign:'New design',
 diameterLabel:'D · parent diameter (mm)',flowLabel:'Q · per inlet (cc/s)',
 rangeCaveat:'Research input limits, not certified accuracy. Gen 2–3 inherit D/Q; branch diameters follow the channel rule.',
 fixedProcess:'Fixed process',createGen1:'Create Gen 1',predictCurrent:'Predict Gen 1',createNext:'Create Gen 2',newChain:'Another design',
 archivedCases:'Re-predict saved cases',continueDesign:'Continue evolution',designReady:'Channels created. Predict this network next.',
 designPredicted:'Prediction complete. You can create the next generation.',designComplete:'Gen 1–3 chain complete.',
 predict_parent_first:'Predict the parent generation before evolving.',design_out_of_range:'D/Q are outside the displayed range.',
 channel_or_mapping_failed:'New channels failed geometry checks. The parent is unchanged.',
 design_prediction_failed:'Prediction failed. The channels are unchanged.',design_not_found:'Design expired. Start a new chain.',
 geometry_design_unavailable:'No published channel recipe for this geometry.',design_cancelled_or_timeout:'Stopped or timed out. The parent is unchanged.',
 subPredict:'Enter D/Q → create channels → predict → evolve Gen 2–3.',privacyNote:'Public edition creates channels, predicts and chats on published geometry. No DOE, training or private datasets.',
 noResultNote:'Create channels, then predict. Results have not passed independent FEA validation.',
 generated:'Created',predicted:'Predicted',waiting:'Not created',view:'View',network:'Channel network',circuits:'Circuits',segments:'Segments',length:'Length (mm)',researchRange:'Input range',lockedDQ:'D/Q stay fixed within a chain. Choose Another design to change them.'
});
let language;
try {language=localStorage.getItem('cooling-language')==='en'?'en':'vi';}catch{language='vi';}
const state={page:'predict',online:false,csrf:'',cases:[],geometries:[],recipes:[],design:null,designHistory:{},geometryId:null,selected:null,result:null,history:[],job:null,chatRow:null,zoom:1,pan:[0,0],installEvent:null,waitingWorker:null,pet:'idle',localPreview:false,temporaryPreview:false};
const t=key=>TEXT[language][key]||TEXT[language].genericError;
const store=(key,value)=>{try{localStorage.setItem(key,value);}catch{}};
function element(tag,text,className){const el=document.createElement(tag);if(text!==undefined)el.textContent=text;if(className)el.className=className;return el;}
function status(id,key,error=false){$(id).textContent=key?t(key):'';$(id).classList.toggle('error',error);}
function pet(value){state.pet=value;$('pet').dataset.state=value;$('thought').textContent=t({idle:'thoughtIdle',running:'thoughtRun',complete:'thoughtDone',offline:'thoughtOffline',error:'thoughtError'}[value]||'thoughtIdle');}
function setOnline(online){state.online=online;$('connection').className='connection '+(online?'online':'offline');$('connection-text').textContent=t(online?'online':'offline');$('network-banner').hidden=online&&!state.localPreview&&!state.temporaryPreview;$('network-banner').textContent=online&&state.temporaryPreview?(language==='vi'?'Link dùng thử · có thể đổi sau khi khởi động lại.':'Preview link · may change after restart.'):t(online?'localPreview':'offlineBanner');if(!state.job){if(!online)pet('offline');else if(state.pet==='offline')pet('idle');}buttons();}
function buttons(){const busy=!!state.job;$('run-prediction').disabled=!state.online||!state.selected?.ready||busy;$('send-question').disabled=!state.online||busy;$('cancel-prediction').hidden=state.job?.kind!=='predict';$('cancel-chat').hidden=state.job?.kind!=='chat';$('export-chat').disabled=!state.history.length;$('update-now').disabled=busy||!!$('question').value.trim();$('update-now').title=$('update-now').disabled?t('updateDeferred'):'';designButtons();}
function page(key,focus=true){if(!['predict','results','assistant','settings'].includes(key))return;state.page=key;for(const el of document.querySelectorAll('.page'))el.hidden=el.id!=='page-'+key;for(const el of document.querySelectorAll('[data-page]')){const selected=el.dataset.page===key;el.classList.toggle('selected',selected);if(selected)el.setAttribute('aria-current','page');else el.removeAttribute('aria-current');}heading();if(focus){$('main').focus({preventScroll:true});window.scrollTo({top:0,behavior:'instant'});}if(key==='results')requestAnimationFrame(drawChart);}
function heading(){const capital=state.page[0].toUpperCase()+state.page.slice(1),title=t('title'+capital);$('page-title').classList.toggle('two-tone',!!title[1]);$('page-title').replaceChildren(element('span',title[0],'title-first'));if(title[1])$('page-title').append(document.createElement('br'),element('span',title[1]));$('page-subtitle').textContent=t('sub'+capital);$('page-subtitle').hidden=state.page==='predict';$('page-index').textContent=String(['predict','results','assistant','settings'].indexOf(state.page)+1).padStart(2,'0')+' / '+t(state.page);}
function applyLanguage(){document.documentElement.lang=language;for(const el of document.querySelectorAll('[data-i18n]'))el.textContent=t(el.dataset.i18n);for(const el of document.querySelectorAll('[data-placeholder]'))el.placeholder=t(el.dataset.placeholder);for(const el of document.querySelectorAll('[data-aria]'))el.setAttribute('aria-label',t(el.dataset.aria));$('language').textContent=language==='vi'?'EN':'VI';$('language').setAttribute('aria-label',language==='vi'?'Switch language to English':'Chuyển sang tiếng Việt');$('language-select').value=language;$('pet').setAttribute('aria-label',t('assistant'));heading();renderCases();details();suggestions();installHelp();setOnline(state.online);pet(state.pet);if(state.result)renderResult();buttons();}
function changeLanguage(value){language=value;store('cooling-language',language);applyLanguage();window.dispatchEvent(new Event('cooling-language'));}
async function api(route,body){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),12000);try{const options={credentials:'same-origin',cache:'no-store',signal:controller.signal};if(body!==undefined)Object.assign(options,{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':state.csrf},body:JSON.stringify(body)});const response=await fetch(route,options);const data=await response.json();if(!response.ok){const err=new Error(data.error||'genericError');err.code=data.error;throw err;}return data;}finally{clearTimeout(timer);}}
async function connect(){try{const health=await api('/api/health');state.localPreview=health.mode==='local_preview';state.temporaryPreview=health.mode==='temporary_public_preview';const session=await api('/api/session');state.csrf=session.csrf;$('version').textContent=session.version;setOnline(true);await catalog();resumeJob();}catch{setOnline(false);}}
async function catalog(){try{const data=await api('/api/catalog');state.cases=data.cases;state.geometries=data.geometries||[];state.recipes=data.design_recipes||[];$('case-count').textContent=String(state.cases.length);if(state.selected)state.selected=state.cases.find(row=>row.id===state.selected.id)||null;renderCases();details();buttons();window.dispatchEvent(new Event('cooling-catalog'));designForm();}catch{setOnline(false);}}
function renderCases(){const filter=$('case-search').value.trim().toLocaleLowerCase(language),rows=state.cases.filter(row=>(!state.geometryId||row.geometry===state.geometryId)&&(row['label_'+language]+' '+row.geometry+' '+row.model_label).toLocaleLowerCase(language).includes(filter));$('case-count').textContent=String(rows.length);$('case-list').replaceChildren();$('empty-cases').hidden=rows.length>0;$('empty-cases').querySelector('h3').textContent=t(rows.length===0&&state.cases.some(row=>!state.geometryId||row.geometry===state.geometryId)?'noMatches':'noCases');for(const row of rows){const button=element('button',undefined,'case-button'+(state.selected?.id===row.id?' selected':''));button.type='button';button.setAttribute('aria-pressed',String(state.selected?.id===row.id));button.append(element('span',row['label_'+language]),element('small',row.geometry+' · '+row.model_label),element('small',row.research_mode?(language==='vi'?'Model nghiên cứu · chưa kiểm định độc lập':'Research model · no independent validation'):t(row.ready?'qualified':'unqualified'),row.research_mode||!row.ready?'unready':''));button.addEventListener('click',()=>{state.selected=row;state.zoom=1;renderCases();details();buttons();status('prediction-status',row.ready?'':'model_not_qualified',!row.ready);document.querySelector('.steps li:nth-child(2)').classList.add('active');});$('case-list').append(button);}}
function displayValue(value){if(typeof value==='number')return Number.isFinite(value)?value.toLocaleString(language==='vi'?'vi-VN':'en-US',{maximumFractionDigits:3}):'—';if(Array.isArray(value))return value.map(displayValue).join(' · ');if(value&&typeof value==='object')return Object.entries(value).map(([k,v])=>k+': '+displayValue(v)).join(' · ');return String(value);}
function dl(target,values){target.replaceChildren();for(const [key,value] of Object.entries(values)){target.append(element('dt',key),element('dd',displayValue(value)));}}
function details(){$('input-empty').hidden=!!state.selected;$('case-details').hidden=!state.selected;if(!state.selected)return;$('selected-label').textContent=state.selected['label_'+language];dl($('input-values'),{[t('geometry')]:state.selected.geometry,[t('model')]:state.selected.model_label,...state.selected.inputs});dl($('process-values'),state.selected.process);}
function suggestions(){$('suggestions').replaceChildren();for(const question of t('questions')){const button=element('button',question);button.type='button';button.addEventListener('click',()=>{$('question').value=question;page('assistant',false);$('question').focus();$('question').scrollIntoView({block:'center',behavior:'smooth'});buttons();});$('suggestions').append(button);}}
function rememberJob(){try{if(state.job)sessionStorage.setItem('cooling-current-job',JSON.stringify({id:state.job.id,kind:state.job.kind}));else sessionStorage.removeItem('cooling-current-job');}catch{}}
function resumeJob(){if(state.job)return;let saved;try{saved=JSON.parse(sessionStorage.getItem('cooling-current-job')||'null');}catch{}if(saved&&/^[\w-]{20,80}$/.test(saved.id)&&['predict','chat','design'].includes(saved.kind)){state.job=saved;if(saved.kind==='chat')state.chatRow=chatRow('',t('reconnecting'));buttons();pollJob();}}
function errorKey(error){return error.code&&TEXT[language][error.code]?error.code:'genericError';}
async function runPrediction(){if(!state.selected||state.job)return;try{state.job=await api('/api/predict',{case_id:state.selected.id});rememberJob();pet('running');status('prediction-status','running');buttons();pollJob();}catch(error){status('prediction-status',errorKey(error),true);pet('error');}}
function chatRow(question,answer=''){const empty=$('chat-messages').querySelector('.empty-chat');if(empty)empty.remove();if(question){const user=element('div',undefined,'message user');user.append(element('strong',t('you')),element('div',question,'text'));$('chat-messages').append(user);}const assistant=element('div',undefined,'message');assistant.append(element('strong',t('petName')));const text=element('div',answer,'text');assistant.append(text);$('chat-messages').append(assistant);return {question,text,element:assistant};}
async function sendQuestion(event){event.preventDefault();if(state.job)return;const question=$('question').value.trim();if(!question){status('chat-status','invalid_question',true);$('question').focus();return;}try{const job=await api('/api/chat',{question,language,history:state.history.slice(-6).map(row=>({question:row.question,answer:row.answer,status:row.status}))});state.chatRow=chatRow(question);state.job=job;$('question').value='';rememberJob();pet('running');status('chat-status','running');buttons();pollJob();}catch(error){status('chat-status',errorKey(error),true);pet('error');}}
let pollTimer=null;
async function pollJob(){if(!state.job)return;const key=state.job.id;try{const job=await api('/api/jobs/'+encodeURIComponent(key));if(state.job?.id!==key)return;setOnline(true);if(job.kind==='chat'&&state.chatRow){const box=$('chat-messages'),nearBottom=box.scrollHeight-box.scrollTop-box.clientHeight<80;smoothAnswer(state.chatRow.text,job.text,box);}if(['complete','error','cancelled'].includes(job.status)){finishJob(job);return;}status(job.kind==='chat'?'chat-status':'prediction-status',job.status==='cancelling'?'cancelling':'running');pet('running');}catch(error){if(error.code==='job_not_found'){finishJob({id:key,kind:state.job.kind,status:'error',error:'job_not_found'});return;}setOnline(false);status(state.job.kind==='chat'?'chat-status':'prediction-status','reconnecting',true);}pollTimer=setTimeout(pollJob,state.job?.kind==='chat'?400:1500);}
function finishJob(job){const good=job.status==='complete';if(job.kind==='chat'){const answer=job.result?.answer||state.chatRow?.text.textContent||'';state.history.push({question:state.chatRow?.question||'',answer,status:job.status,created_at:job.created_at||new Date().toISOString(),elapsed_seconds:job.result?.elapsed_seconds,local_llm_used:job.result?.local_llm_used||false});if(state.chatRow){smoothAnswer(state.chatRow.text,answer||(good?'':t(job.error||'request_failed')),$('chat-messages'));state.chatRow.element.dataset.status=job.status;}status('chat-status',good?'complete':job.status==='cancelled'?'cancelled':job.error||'request_failed',!good);}else if(good){state.result=job.result;state.zoom=1;state.pan=[0,0];renderResult();page('results');status('prediction-status','complete');document.querySelector('.steps li:nth-child(3)').classList.add('active');}else status('prediction-status',job.status==='cancelled'?'cancelled':job.error||'request_failed',true);state.job=null;rememberJob();pet(good?'complete':job.status==='cancelled'?'idle':'error');buttons();}
async function cancelJob(){if(!state.job)return;try{await api('/api/jobs/'+encodeURIComponent(state.job.id)+'/cancel',{});status(state.job.kind==='chat'?'chat-status':'prediction-status','cancelling');}catch(error){status(state.job.kind==='chat'?'chat-status':'prediction-status',errorKey(error),true);}}
function resultLabel(){const result=state.result;if(result?.design_id)return (state.geometries.find(g=>g.id===result.geometry_id)?.['label_'+language]||result.geometry_id)+' · Gen '+result.generation+' · D '+displayValue(result.D_mm)+' mm · Q '+displayValue(result.Q_cc_s)+' cc/s';return result?.['case_label_'+language]||state.cases.find(row=>row.id===result?.case_id)?.['label_'+language]||result?.case_id||'';}
function renderResult(){if(!state.result)return;$('result-empty').hidden=true;$('result-content').hidden=false;const result=state.result;$('metrics').replaceChildren();for(const [name,value] of [['min',result.min_C],['max',result.max_C],['mean',result.surface_mean_C]]){const card=element('div',undefined,'metric');card.append(element('span',t(name)),element('strong',Number(value).toLocaleString(language==='vi'?'vi-VN':'en-US',{minimumFractionDigits:2,maximumFractionDigits:2})+' °C'));$('metrics').append(card);}$('result-label').textContent=resultLabel()+' · '+result.model;document.querySelector('[data-i18n="projection"]').textContent=(language==='vi'?'Bề mặt · hình chiếu ':'Surface · projection ')+result.projection+(language==='vi'?' · điểm lấy mẫu':' · sampled points');$('legend-min').textContent=Number(result.min_C).toFixed(2)+' °C';$('legend-max').textContent=Number(result.max_C).toFixed(2)+' °C';requestAnimationFrame(drawChart);}
function drawChart(){if(!state.result||state.page!=='results')return;const canvas=$('result-chart'),rect=canvas.getBoundingClientRect(),dpr=Math.min(window.devicePixelRatio||1,2);if(rect.width<1)return;canvas.width=Math.round(rect.width*dpr);canvas.height=Math.round(rect.height*dpr);paint(canvas,state.result,dpr,rect.width,rect.height,state.zoom,state.pan);}
function paint(canvas,result,dpr,width,height,zoom,pan){const ctx=canvas.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);ctx.fillStyle='#050808';ctx.fillRect(0,0,width,height);const points=result.points||[],temperatures=result.temperature_C||[];if(!points.length)return;const axes=result.projection_axes||[0,1],xs=points.map(p=>p[axes[0]]),ys=points.map(p=>p[axes[1]]),loX=Math.min(...xs),hiX=Math.max(...xs),loY=Math.min(...ys),hiY=Math.max(...ys);const scale=Math.min((width-40)/Math.max(hiX-loX,1),(height-40)/Math.max(hiY-loY,1))*zoom,cx=(loX+hiX)/2,cy=(loY+hiY)/2;const range=Math.max(result.max_C-result.min_C,1e-9);ctx.save();ctx.beginPath();ctx.rect(0,0,width,height);ctx.clip();points.forEach((point,index)=>{const fraction=Math.min(1,Math.max(0,(temperatures[index]-result.min_C)/range));ctx.fillStyle=`hsl(${230*(1-fraction)},85%,57%)`;ctx.beginPath();ctx.arc(width/2+(point[axes[0]]-cx)*scale+pan[0],height/2-(point[axes[1]]-cy)*scale+pan[1],Math.min(4,Math.max(1.2,width/350)),0,Math.PI*2);ctx.fill();});ctx.restore();}
function download(name,data,type){const direct=name==='cooling-ai-result.json'&&/^[\w-]{20,80}$/.test(state.result?.job_id||'');const url=direct?'/api/jobs/'+state.result.job_id+'/export':URL.createObjectURL(new Blob([data],{type}));const a=element('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();if(!direct)setTimeout(()=>URL.revokeObjectURL(url),30000);}
function exportChart(){if(!state.result)return;const canvas=document.createElement('canvas');canvas.width=1800;canvas.height=1100;paint(canvas,state.result,1,1800,1000,1,[0,0]);const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,1000,1800,100);ctx.fillStyle='#121817';ctx.font='26px Arial';ctx.fillText(`${state.result.model} · ${state.result.case_id} · ${state.result.projection} sample · ${state.result.min_C.toFixed(2)}–${state.result.max_C.toFixed(2)} °C`,30,1040);ctx.font='20px Arial';ctx.fillText('AI prediction · not FEA / not independent validation',30,1080);canvas.toBlob(blob=>{if(blob)download('cooling-ai-projection.png',blob,'image/png');});}
function installHelp(){const standalone=window.matchMedia('(display-mode: standalone)').matches||window.navigator.standalone||state.installed;const ios=/iPad|iPhone|iPod/.test(navigator.userAgent)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1);$('install-help').textContent=t(standalone?'standalone':!window.isSecureContext?'secureInstall':ios?'iosInstall':'browserInstall');$('install').disabled=!!standalone;$('install').textContent=t(standalone?'installed':state.installEvent?'install':'installGuide');$('install-help').setAttribute('tabindex','-1');}
async function install(){const event=state.installEvent;if(event){try{await event.prompt();const choice=await event.userChoice;state.installEvent=null;installHelp();if(choice.outcome==='dismissed')$('install-help').textContent=t('installDismissed');}catch{state.installEvent=null;installHelp();$('install-help').textContent=t('installFailed');}}else installHelp();$('install-help').focus();}
window.addEventListener('appinstalled',()=>{state.installed=true;state.installEvent=null;installHelp();});
function motion(){let saved;try{saved=localStorage.getItem('cooling-reduced-motion');}catch{}const reduce=saved==='true'||(saved===null&&window.matchMedia('(prefers-reduced-motion: reduce)').matches);$('reduced-motion').checked=reduce;document.body.classList.toggle('reduced-motion',reduce);}
async function serviceWorker(){if(!('serviceWorker' in navigator)||!window.isSecureContext)return;try{const registration=await navigator.serviceWorker.register('/user/sw.js',{scope:'/user/'});let applied=false,reloading=false;const show=()=>{state.waitingWorker=registration.waiting;$('update-banner').hidden=!state.waitingWorker;buttons();};show();registration.addEventListener('updatefound',()=>{registration.installing?.addEventListener('statechange',()=>{if(navigator.serviceWorker.controller)show();});});$('update-now').addEventListener('click',()=>{if(state.waitingWorker&&!state.job&&!$('question').value.trim())applied=true;});navigator.serviceWorker.addEventListener('controllerchange',()=>{if(applied&&!reloading&&!state.job&&!$('question').value.trim()){reloading=true;window.location.reload();}});}catch{/* Installation is optional; regular browser mode remains usable. */}}
function keyboard(){if(!window.visualViewport)return;const focused=document.activeElement?.matches('textarea,input,select'),covered=window.innerHeight-window.visualViewport.height>140;document.body.classList.toggle('keyboard-open',!!focused&&covered);}
for(const el of document.querySelectorAll('[data-page]'))el.addEventListener('click',()=>page(el.dataset.page));for(const el of document.querySelectorAll('[data-go]'))el.addEventListener('click',()=>page(el.dataset.go));$('pet').addEventListener('click',()=>page('assistant'));$('language').addEventListener('click',()=>changeLanguage(language==='vi'?'en':'vi'));$('language-select').addEventListener('change',event=>changeLanguage(event.target.value));$('case-search').addEventListener('input',renderCases);$('refresh').addEventListener('click',connect);$('run-prediction').addEventListener('click',runPrediction);$('chat-form').addEventListener('submit',sendQuestion);$('question').addEventListener('input',buttons);$('cancel-chat').addEventListener('click',cancelJob);$('cancel-prediction').addEventListener('click',cancelJob);$('export-result').addEventListener('click',()=>download('cooling-ai-result.json',JSON.stringify({exported_at:new Date().toISOString(),...state.result},null,2),'application/json'));$('export-chat').addEventListener('click',()=>download('cooling-ai-chat.json',JSON.stringify({exported_at:new Date().toISOString(),language,source:'master_local_llm',scientific_validation:false,conversation:state.history},null,2),'application/json'));$('export-chart').addEventListener('click',exportChart);$('zoom-in').addEventListener('click',()=>{state.zoom=Math.min(8,state.zoom*1.3);drawChart();});$('zoom-out').addEventListener('click',()=>{state.zoom=Math.max(.5,state.zoom/1.3);drawChart();});$('zoom-reset').addEventListener('click',()=>{state.zoom=1;state.pan=[0,0];drawChart();});$('reduced-motion').addEventListener('change',event=>{store('cooling-reduced-motion',String(event.target.checked));motion();});$('install').addEventListener('click',install);$('update-now').addEventListener('click',()=>{if(!state.job&&!$('question').value.trim())state.waitingWorker?.postMessage('APPLY_UPDATE');});window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();state.installEvent=event;installHelp();});window.addEventListener('appinstalled',installHelp);window.addEventListener('offline',()=>setOnline(false));window.addEventListener('online',connect);window.addEventListener('resize',()=>{drawChart();keyboard();});window.visualViewport?.addEventListener('resize',keyboard);document.addEventListener('focusin',keyboard);document.addEventListener('focusout',()=>setTimeout(keyboard,100));document.addEventListener('visibilitychange',()=>{document.body.classList.toggle('reduced-motion-hidden',document.hidden);if(!document.hidden)connect();});
let drag=null;$('result-chart').addEventListener('pointerdown',event=>{if(event.pointerType==='mouse'&&state.zoom>1){drag=[event.clientX,event.clientY];event.target.setPointerCapture(event.pointerId);}});$('result-chart').addEventListener('pointermove',event=>{if(drag){state.pan[0]+=event.clientX-drag[0];state.pan[1]+=event.clientY-drag[1];drag=[event.clientX,event.clientY];drawChart();}});$('result-chart').addEventListener('pointerup',()=>{drag=null;});$('result-chart').addEventListener('pointercancel',()=>{drag=null;});
function recipe(){return state.recipes.find(row=>row.geometry_id===state.geometryId);}
function designButtons(){const row=state.design,busy=!!state.job,ready=state.online&&!!recipe();$('create-design').disabled=!ready||busy||!!row;$('predict-design').disabled=!ready||busy||!row||row.predicted;$('next-design').disabled=!ready||busy||!row?.predicted||row.generation>=3;$('reset-design').disabled=busy;$('design-d').readOnly=$('design-q').readOnly=!!row||busy;$('cancel-design').hidden=state.job?.kind!=='design';$('predict-design').textContent=(language==='vi'?'Dự đoán Gen ':'Predict Gen ')+(row?.generation||1);$('next-design').textContent=(language==='vi'?'Tạo Gen ':'Create Gen ')+Math.min(3,(row?.generation||1)+1);$('continue-design').hidden=!state.result?.design_id;}
function designForm(){const current=recipe();if(current&&$('design-form').dataset.geometry!==state.geometryId){$('design-form').dataset.geometry=state.geometryId;$('design-d').value=current.default_D_mm;$('design-q').value=current.default_Q_cc_s;for(const [id,bounds]of [['design-d',current.D_range_mm],['design-q',current.Q_range_cc_s]]){$(id).min=bounds[0];$(id).max=bounds[1];}}if(current){$('d-bounds').textContent=current.D_range_mm.join('–')+' mm';$('q-bounds').textContent=current.Q_range_cc_s.join('–')+' cc/s / inlet';dl($('design-process'),{...current.process,'Gen1 H':'Original · D(3-x)','Tref (°C)':current.reference_temperature_C,[t('model')]:current.model_label});}renderDesign();}
function renderDesign(){const row=state.design;$('design-generation').textContent='GEN '+(row?.generation||1);$('design-timeline').replaceChildren();for(let g=1;g<=3;g++){const old=state.designHistory[g],card=element('div',undefined,'generation-card'+(row?.generation===g?' current':''));card.append(element('b','GEN '+g),element('small',t(old?.predicted?'predicted':old?'generated':'waiting')));if(old?.predicted){const view=element('button',t('view'));view.type='button';view.addEventListener('click',()=>{state.result=old;renderResult();page('results');});card.append(view);}$('design-timeline').append(card);}$('design-summary').hidden=!row;if(row){$('design-d').value=row.D_mm;$('design-q').value=row.Q_cc_s;$('design-summary').replaceChildren(element('h3',t('network')+' · Gen '+row.generation));const values=element('dl',undefined,'value-grid');dl(values,{[t('circuits')]:row.circuit_count,[t('segments')]:row.segment_count,[t('length')]:row.length_mm});$('design-summary').append(values,element('p',t('lockedDQ'),'subtle'));}designButtons();window.dispatchEvent(new Event('cooling-design'));}
function rememberDesign(){try{if(state.design)sessionStorage.setItem('cooling-design',JSON.stringify(state.design));else sessionStorage.removeItem('cooling-design');}catch{}}
function resetDesign(){if(state.job)return;state.design=null;state.designHistory={};rememberDesign();status('design-status','');renderDesign();}
async function runDesign(action){if(state.job||!recipe())return;let payload;if(!state.design){if(action!=='generate'||!$('design-form').reportValidity())return;payload={action,generation:1,geometry_id:state.geometryId,D_mm:Number($('design-d').value),Q_cc_s:Number($('design-q').value)};}else payload={action,generation:state.design.generation+(action==='generate'?1:0),design_id:state.design.design_id};try{state.job=await api('/api/design',payload);rememberJob();pet('running');status('design-status','running');buttons();pollJob();}catch(error){status('design-status',errorKey(error),true);pet('error');}}
function finishDesign(job){const good=job.status==='complete';if(good){state.design=job.result;state.geometryId=job.result.geometry_id;state.designHistory[job.result.generation]=job.result;rememberDesign();window.dispatchEvent(new Event('cooling-catalog'));renderDesign();status('design-status',job.result.predicted?(job.result.generation===3?'designComplete':'designPredicted'):'designReady');if(job.result.predicted){state.result=job.result;renderResult();window.dispatchEvent(new Event('cooling-prediction'));}else page('predict',false);}else status('design-status',job.status==='cancelled'?'cancelled':job.error||'request_failed',true);state.job=null;rememberJob();pet(good?'complete':'error');buttons();}
const originalFinishJob=finishJob;finishJob=function(job){if(job.kind==='design')finishDesign(job);else originalFinishJob(job);};
window.addEventListener('cooling-language',designForm);window.addEventListener('cooling-geometry',()=>{if(state.design?.geometry_id!==state.geometryId){state.design=null;state.designHistory={};rememberDesign();}designForm();});
$('design-form').addEventListener('submit',event=>{event.preventDefault();runDesign('generate');});$('predict-design').addEventListener('click',()=>runDesign('predict'));$('next-design').addEventListener('click',()=>runDesign('generate'));$('reset-design').addEventListener('click',resetDesign);$('cancel-design').addEventListener('click',cancelJob);
try{const saved=JSON.parse(sessionStorage.getItem('cooling-design')||'null');if(saved&&/^[\w-]{20,80}$/.test(saved.design_id)&&[1,2,3].includes(saved.generation)){state.design=saved;state.geometryId=saved.geometry_id;state.designHistory[saved.generation]=saved;if(saved.predicted)state.result=saved;}}catch{}
applyLanguage();motion();connect();serviceWorker();setInterval(()=>{if(!document.hidden&&!state.job)connect();},30000);
