/* Real STEP surface previews. No external library/CDN, no geometry scaling for physics. */
'use strict';
(() => {
 const canvas=$('geometry-canvas'),cache=new Map();
 const gl=canvas.getContext('webgl',{alpha:true,antialias:true,preserveDrawingBuffer:false});
 let yaw=.18,pitch=1.16,zoom=1,current=null,selectedIndex=-1,loadId=0,lastFrame=0,drag=null;
 const vi=()=>language==='vi';
 function message(value){$('geometry-loading').textContent=value;$('geometry-loading').hidden=!value;}
 function labels(){
  $('garage-title').textContent=vi()?'Chọn chi tiết':'Choose geometry';
  $('geometry-prev').setAttribute('aria-label',vi()?'Chi tiết trước':'Previous geometry');
  $('geometry-next').setAttribute('aria-label',vi()?'Chi tiết tiếp theo':'Next geometry');
  canvas.setAttribute('aria-label',vi()?'Xem chi tiết 3D; kéo ngang để xoay, dùng phím mũi tên để xoay':'3D preview; drag horizontally or use arrow keys to rotate');
  $('garage-hint').textContent=vi()?'Một ngón xoay · hai ngón thu/phóng · chạm đúp để khớp hình.':'Drag to rotate · pinch to zoom · double-tap to fit.';
  info();cards();
 }
 let program,positionBuffer,normalBuffer,count=0,locations,available=!!gl;
 let channelPosition,channelNormal,channelCount=0,channelKey=null,fit=1;
 function initialize(){
 if(gl){try{
  const compile=(type,source)=>{const shader=gl.createShader(type);gl.shaderSource(shader,source);gl.compileShader(shader);if(!gl.getShaderParameter(shader,gl.COMPILE_STATUS))throw new Error('Preview shader failed');return shader;};
  program=gl.createProgram();
  gl.attachShader(program,compile(gl.VERTEX_SHADER,`attribute vec3 position; attribute vec3 normal; uniform mat3 rotation; uniform vec2 scale; varying vec3 n; varying vec3 p; void main(){vec3 q=rotation*position;n=rotation*normal;p=q;gl_Position=vec4(q.x*scale.x,q.y*scale.y,-q.z*0.25,1.0);}`));
  gl.attachShader(program,compile(gl.FRAGMENT_SHADER,`precision mediump float;uniform bool channel;varying vec3 n;varying vec3 p;void main(){vec3 norm=normalize(n);float light=0.35+0.65*abs(dot(norm,normalize(vec3(-0.4,0.8,1.0))));float edge=pow(1.0-abs(norm.z),2.0);vec3 metal=channel?mix(vec3(0.24,0.09,0.04),vec3(0.98,0.55,0.25),light):mix(vec3(0.10,0.40,0.32),vec3(0.49,0.77,0.65),light);metal+=edge*vec3(0.15,0.18,0.16);gl_FragColor=vec4(metal,1.0);}`));
  gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw new Error('Preview program failed');
  locations={position:gl.getAttribLocation(program,'position'),normal:gl.getAttribLocation(program,'normal'),rotation:gl.getUniformLocation(program,'rotation'),scale:gl.getUniformLocation(program,'scale'),channel:gl.getUniformLocation(program,'channel')};
  positionBuffer=gl.createBuffer();normalBuffer=gl.createBuffer();channelPosition=gl.createBuffer();channelNormal=gl.createBuffer();gl.enable(gl.DEPTH_TEST);gl.disable(gl.CULL_FACE);
 }catch{available=false;message(vi()?'Chưa mở được hình 3D. Vẫn chọn case được.':'3D preview unavailable. Case selection still works.');}}
 else message(vi()?'Máy không hỗ trợ WebGL. Vẫn chọn case và dự đoán được.':'WebGL is unavailable. Case selection and prediction still work.');
 }
 initialize();
 function rotation(){const c=Math.cos(yaw),s=Math.sin(yaw),a=Math.cos(pitch),b=Math.sin(pitch);return new Float32Array([c,s*b,-s*a,0,a,b,s,-c*b,c*a]);}
 function draw(){if(!available||!program||!current)return;const rect=canvas.getBoundingClientRect();if(rect.width<1||rect.height<1)return;const dpr=Math.min(window.devicePixelRatio||1,2),w=Math.round(rect.width*dpr),h=Math.round(rect.height*dpr);if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;}gl.viewport(0,0,w,h);gl.clearColor(0,0,0,0);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.useProgram(program);gl.uniformMatrix3fv(locations.rotation,false,rotation());const size=.82*zoom/fit;gl.uniform2f(locations.scale,size,size*(w/h));for(const [p,n,length,tube]of [[positionBuffer,normalBuffer,count,false],[channelPosition,channelNormal,channelCount,true]]){if(!length)continue;gl.uniform1i(locations.channel,tube?1:0);for(const [buffer,key]of [[p,'position'],[n,'normal']]){gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.enableVertexAttribArray(locations[key]);gl.vertexAttribPointer(locations[key],3,gl.FLOAT,false,0,0);}gl.drawArrays(gl.TRIANGLES,0,length);}}
 function channels(){if(!available)return;const row=state.design?.geometry_id===state.geometryId?state.design:null,key=row?.network_fingerprint||null;if(channelKey===key)return;channelKey=key;channelCount=0;fit=1;if(!row){draw();return;}const vertices=[],normals=[],center=row.display_center_mm,scale=row.display_scale,sides=16;const unit=v=>{const length=Math.hypot(...v)||1;return v.map(x=>x/length);},cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]];for(const segment of row.segments||[]){const line=segment.centerline_mm,radius=segment.diameter_mm*scale/2,rings=[];for(let i=0;i<line.length;i++){const a=line[Math.max(0,i-1)],b=line[Math.min(line.length-1,i+1)],tangent=unit(b.map((x,k)=>x-a[k])),u=unit(cross(tangent,Math.abs(tangent[2])>.9?[0,1,0]:[0,0,1])),v=cross(tangent,u),point=line[i].map((x,k)=>(x-center[k])*scale);const ring=[];for(let j=0;j<sides;j++){const angle=2*Math.PI*j/sides,n=u.map((x,k)=>x*Math.cos(angle)+v[k]*Math.sin(angle)),p=point.map((x,k)=>x+radius*n[k]);fit=Math.max(fit,Math.hypot(...p));ring.push({p,n});}rings.push(ring);}for(let i=1;i<rings.length;i++)for(let j=0;j<sides;j++){const k=(j+1)%sides,a=rings[i-1][j],b=rings[i][j],c=rings[i][k],d=rings[i-1][k];for(const node of [a,b,c,a,c,d]){vertices.push(...node.p);normals.push(...node.n);}}}gl.bindBuffer(gl.ARRAY_BUFFER,channelPosition);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(vertices),gl.STATIC_DRAW);gl.bindBuffer(gl.ARRAY_BUFFER,channelNormal);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(normals),gl.STATIC_DRAW);channelCount=vertices.length/3;draw();}
 function upload(vertices){const normals=new Float32Array(vertices.length);for(let i=0;i<vertices.length;i+=9){const ax=vertices[i+3]-vertices[i],ay=vertices[i+4]-vertices[i+1],az=vertices[i+5]-vertices[i+2],bx=vertices[i+6]-vertices[i],by=vertices[i+7]-vertices[i+1],bz=vertices[i+8]-vertices[i+2],x=ay*bz-az*by,y=az*bx-ax*bz,z=ax*by-ay*bx,len=Math.hypot(x,y,z)||1;for(let j=0;j<9;j+=3){normals[i+j]=x/len;normals[i+j+1]=y/len;normals[i+j+2]=z/len;}}gl.bindBuffer(gl.ARRAY_BUFFER,positionBuffer);gl.bufferData(gl.ARRAY_BUFFER,vertices,gl.STATIC_DRAW);gl.bindBuffer(gl.ARRAY_BUFFER,normalBuffer);gl.bufferData(gl.ARRAY_BUFFER,normals,gl.STATIC_DRAW);count=vertices.length/3;draw();}
 function info(){const row=state.geometries[selectedIndex];$('geometry-counter').textContent=row?(selectedIndex+1)+' / '+state.geometries.length:'0 / 0';$('geometry-name').textContent=row?row['label_'+language]:'—';$('geometry-size').textContent=row?row.dimensions_mm.map(n=>Number(n).toFixed(1)).join(' × ')+' mm':'—';$('geometry-prev').disabled=$('geometry-next').disabled=state.geometries.length<2;}
 function cards(){const target=$('geometry-cards');target.replaceChildren();state.geometries.forEach((row,index)=>{const button=element('button',undefined,'geometry-card'+(index===selectedIndex?' selected':''));button.type='button';button.setAttribute('aria-pressed',String(index===selectedIndex));button.append(element('span',String(index+1).padStart(2,'0'),'garage-number'),element('b',row['label_'+language]),element('small',row.id));button.addEventListener('click',()=>select(index));target.append(button);});}
 async function select(index){if(!state.geometries.length)return;selectedIndex=(index+state.geometries.length)%state.geometries.length;const row=state.geometries[selectedIndex];state.geometryId=row.id;if(state.selected?.geometry!==row.id){state.selected=null;details();buttons();}renderCases();info();cards();yaw=.18;pitch=1.16;zoom=1;current=null;const ticket=++loadId;if(available){gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);message(vi()?'Đang tải hình…':'Loading preview…');try{let vertices=cache.get(row.id);if(!vertices){const response=await fetch('/api/geometry/'+encodeURIComponent(row.id),{cache:'no-store'});if(!response.ok)throw new Error('Preview unavailable');const data=await response.arrayBuffer();if(data.byteLength%36||data.byteLength>2200000)throw new Error('Preview invalid');vertices=new Float32Array(data);if(!vertices.every(Number.isFinite))throw new Error('Preview invalid');cache.set(row.id,vertices);while(cache.size>4)cache.delete(cache.keys().next().value);}if(ticket!==loadId)return;current=vertices;upload(vertices);message('');}catch{if(ticket===loadId)message(vi()?'Chưa tải được hình. Hãy kiểm tra kết nối.':'Preview unavailable. Check the connection.');}}
 }
 const selectGeometry=select;select=async function(index){if(state.job?.kind==='design')return;const previous=state.geometryId,loading=selectGeometry(index);if(previous!==state.geometryId)window.dispatchEvent(new Event('cooling-geometry'));await loading;channels();};
 function catalog(){if(!state.geometries.length){info();cards();return;}const found=state.geometries.findIndex(row=>row.id===state.geometryId);const index=found>=0?found:0;if(index===selectedIndex&&current){info();cards();return;}select(index);}
 $('geometry-prev').addEventListener('click',()=>select(selectedIndex-1));$('geometry-next').addEventListener('click',()=>select(selectedIndex+1));
 const pointers=new Map();let distance=0,lastTap=0,tapStart=null;
 const separation=()=>{const p=[...pointers.values()];return p.length===2?Math.hypot(p[0][0]-p[1][0],p[0][1]-p[1][1]):0;};
 const fitView=()=>{yaw=.18;pitch=1.16;zoom=1;draw();};
 canvas.addEventListener('pointerdown',event=>{if(event.pointerType==='mouse'&&event.button!==0)return;pointers.set(event.pointerId,[event.clientX,event.clientY]);canvas.setPointerCapture(event.pointerId);drag=pointers.size===1?[event.clientX,event.clientY]:true;distance=separation();tapStart=pointers.size===1?[event.clientX,event.clientY,performance.now()]:null;});
 canvas.addEventListener('pointermove',event=>{if(!pointers.has(event.pointerId))return;const previous=pointers.get(event.pointerId);pointers.set(event.pointerId,[event.clientX,event.clientY]);if(pointers.size===1){yaw+=(event.clientX-previous[0])*.012;pitch+=(event.clientY-previous[1])*.009;}else if(pointers.size===2){const next=separation();if(distance>0&&next>0)zoom=Math.max(.35,Math.min(6,zoom*next/distance));distance=next;}if(tapStart&&Math.hypot(event.clientX-tapStart[0],event.clientY-tapStart[1])>8)tapStart=null;draw();});
 function release(event){if(!pointers.has(event.pointerId))return;if(event.type==='pointerup'&&tapStart&&performance.now()-tapStart[2]<300){const now=performance.now();if(lastTap&&now-lastTap<320){fitView();lastTap=0;}else lastTap=now;}else lastTap=0;tapStart=null;pointers.delete(event.pointerId);distance=separation();drag=pointers.size?true:null;}
 for(const event of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(event,release);
 window.addEventListener('blur',()=>{pointers.clear();drag=null;distance=0;tapStart=null;});
 canvas.addEventListener('wheel',event=>{event.preventDefault();const delta=event.deltaY*(event.deltaMode===1?16:event.deltaMode===2?200:1);zoom=Math.max(.35,Math.min(6,zoom*Math.exp(-delta*.001)));draw();},{passive:false});
 canvas.addEventListener('keydown',event=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','=','-','0'].includes(event.key))return;event.preventDefault();if(event.key==='ArrowLeft')yaw-=.15;if(event.key==='ArrowRight')yaw+=.15;if(event.key==='ArrowUp')pitch+=.15;if(event.key==='ArrowDown')pitch-=.15;if(['+','='].includes(event.key))zoom=Math.min(6,zoom*1.2);if(event.key==='-')zoom=Math.max(.35,zoom/1.2);if(event.key==='0')fitView();draw();});
 // A distinct swipe strip: rotating the model never unexpectedly selects a different geometry.
 let swipe=null;$('geometry-cards').addEventListener('touchstart',event=>{swipe=event.touches[0].clientX;},{passive:true});$('geometry-cards').addEventListener('touchend',event=>{if(swipe===null)return;const dx=event.changedTouches[0].clientX-swipe;swipe=null;if(Math.abs(dx)>55)select(selectedIndex+(dx<0?1:-1));},{passive:true});
 canvas.addEventListener('webglcontextlost',event=>{event.preventDefault();available=false;message(vi()?'Tạm mất hiển thị 3D. Danh sách case vẫn dùng được.':'3D temporarily unavailable. Case selection still works.');});
 canvas.addEventListener('webglcontextrestored',()=>{available=true;initialize();channelKey=null;channels();if(available&&current){upload(current);message('');}});
 window.addEventListener('resize',draw);window.addEventListener('cooling-catalog',catalog);window.addEventListener('cooling-language',labels);window.addEventListener('cooling-design',channels);function frame(now){if(now-lastFrame>33){lastFrame=now;if(state.page==='predict'&&!document.hidden){if(!document.body.classList.contains('reduced-motion')&&!window.matchMedia('(prefers-reduced-motion: reduce)').matches&&!drag){yaw+=.004;}draw();}}requestAnimationFrame(frame);}labels();catalog();requestAnimationFrame(frame);
})();
